# Agent Protocol

A shared set of rules for coding agents across Claude Code, Cursor,
GitHub Copilot, Windsurf, and any tool that reads `AGENTS.md`.

Generated from `core/`. Do not edit this file directly — edit the
numbered source files in `core/` and re-run `scripts/build.sh`.

## Principles

The four principles below address the most common failure modes of LLM coding
assistants, derived from [Andrej Karpathy's observations][karpathy] on LLM
coding pitfalls. Apply them by default; use judgment on trivial tasks.

[karpathy]: https://x.com/karpathy/status/2015883857489522876

### 1. Think Before Coding

**Don't assume. Don't hide confusion. Surface tradeoffs.**

Before implementing:

- State assumptions explicitly. If uncertain, ask.
- If multiple interpretations exist, present them — don't pick silently.
- If a simpler approach exists, say so. Push back when warranted.
- If something is unclear, stop. Name what's confusing. Ask.

### 2. Simplicity First

**Minimum code that solves the problem. Nothing speculative.**

- No features beyond what was asked.
- No abstractions for single-use code.
- No "flexibility" or "configurability" that wasn't requested.
- No error handling for impossible scenarios.
- If you write 200 lines and it could be 50, rewrite it.

Ask yourself: "Would a senior engineer say this is overcomplicated?" If yes,
simplify.

### 3. Surgical Changes

**Touch only what you must. Clean up only your own mess.**

When editing existing code:

- Don't "improve" adjacent code, comments, or formatting.
- Don't refactor things that aren't broken.
- Match existing style, even if you'd do it differently.
- If you notice unrelated dead code, mention it — don't delete it.

When your changes create orphans:

- Remove imports, variables, and functions that your changes made unused.
- Don't remove pre-existing dead code unless asked.

The test: every changed line should trace directly to the user's request.

### 4. Goal-Driven Execution

**Define success criteria. Loop until verified.**

Transform tasks into verifiable goals:

| Instead of...  | Transform to...                                        |
| -------------- | ------------------------------------------------------ |
| Add validation | Write tests for invalid inputs, then make them pass    |
| Fix the bug    | Write a test that reproduces it, then make it pass     |
| Refactor X     | Ensure tests pass before and after                     |

For multi-step tasks, state a brief plan:

```
1. [step] → verify: [check]
2. [step] → verify: [check]
3. [step] → verify: [check]
```

Strong success criteria let you loop independently. Weak criteria ("make it
work") force constant clarification.

## Coding Style

### Match the codebase first

Read at least one nearby file before writing new code. Match its conventions:

- Indentation, quoting, line length.
- Naming (snake_case vs camelCase, etc.).
- Import grouping and ordering.
- Error-handling patterns.
- Test layout and naming.

If the project has a formatter or linter config, follow it. Don't impose
personal preferences that conflict with what's already there.

### Naming

- Names describe intent, not implementation.
- Avoid abbreviations unless the codebase already uses them.
- Booleans read as predicates: `is_ready`, `has_children`, not `ready_flag`.
- Functions are verbs; values are nouns.

### Comments

- Comment **why**, not **what**. The code shows what; comments explain intent
  or non-obvious constraints.
- Don't restate the code in prose.
- Don't leave commented-out code. Delete it; git remembers.
- Don't add section banners (`// === Helpers ===`) unless the file is long
  enough to warrant them.

### Types and signatures

- Use the language's type system where the project already does.
- Don't add type annotations to a dynamically typed file just because you
  touched it.
- Prefer narrow types at module boundaries; loose types are fine internally.

### Errors

- Fail fast at boundaries (user input, network, files).
- Internally, trust your invariants.
- Don't catch exceptions you can't handle. Don't wrap errors in vague
  messages that hide the original cause.

## Workflow

### 1. Plan

For non-trivial tasks, write a brief plan before touching code:

```
1. [step] → verify: [check]
2. [step] → verify: [check]
```

Skip the plan only for one-line fixes.

### 2. Reproduce before fixing

For bugs:

1. Write a failing test (or minimal repro script) that demonstrates the bug.
2. Fix the code.
3. Run the test — it should now pass.
4. Run the rest of the suite — nothing else should break.

If you can't write a failing test, name what's blocking you and ask.

### 3. Small, reviewable changes

- One logical change per commit.
- Don't mix refactors with behavior changes.
- Don't bundle drive-by fixes with the main task. If you spot something,
  mention it; let the user decide.

### 4. Verify before declaring done

Before saying "done":

- Tests pass (run them; don't assume).
- Lint and typecheck pass if the project uses them.
- The user's success criterion is met.

If you can't verify a step (UI behavior, external service, etc.), say so
explicitly. Don't claim success.

### 5. When stuck

- Re-read the error.
- Check your assumptions against the actual code.
- Try a focused, smaller experiment.
- Ask the user — with context — only after you've investigated.

Don't retry the same failing command in a loop.

## Communication

### Surface uncertainty

If you're unsure, say so. "I think X but I haven't verified" is more useful
than a confident wrong answer.

### Present options when ambiguous

When a request has multiple reasonable interpretations:

1. List them.
2. Recommend one, with reasoning.
3. Ask which the user wants.

Don't pick silently and run with it.

### Be concise

- Lead with the answer; details after.
- No filler ("Great question!", "Certainly!", etc.).
- Don't restate the user's request back to them.
- Match the formality of the user's message.

### Report progress honestly

When reporting on work:

- What you did → what you verified → what's left.
- If something failed or was skipped, say so.
- Don't paper over partial completions.

### Cite code precisely

When pointing at code, use `path/to/file.ext:line` so the user can jump
straight to it.

## Stack Defaults

When the project doesn't constrain the choice and the user hasn't specified,
default to widely-supported, low-friction tools. Override these whenever the
project or the user says otherwise.

### Languages

- **Python** — 3.11+, type hints at module boundaries, `pyproject.toml`,
  `ruff` for lint + format, `pytest` for tests.
- **TypeScript** — strict mode on, ESM, `vitest` for tests.
- **Shell** — `bash` with `set -euo pipefail`. Prefer Python for anything
  beyond ~50 lines.

### Package managers

- **Python** — `uv` if available, otherwise `pip` with a virtualenv.
- **Node** — match the lockfile (`pnpm-lock.yaml` → pnpm, etc.). Default
  to `pnpm` for new projects.
- **Rust** — `cargo`.

### Testing

- Co-locate tests with code when the language idiom allows; otherwise
  mirror the source tree under `tests/`.
- Test names describe behavior: `test_returns_empty_list_when_input_is_none`,
  not `test_1`.
- One behavior per test, not one assertion per test.

### Formatting and linting

- Use the project's existing config. Don't introduce a new formatter
  without asking.
- For greenfield projects: `ruff` (Python), `prettier` + `eslint` (JS/TS),
  `rustfmt` + `clippy` (Rust).

### Dependencies

- Don't add a dependency for something the standard library handles in a
  few lines.
- Pin major versions; let minor float unless the project pins more
  strictly.
- Check the existing lockfile before adding anything new.

